package com.sjstudioz.parkingpin.identity

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import kotlinx.coroutines.CancellationException

/** What the account layer needs from a provider: a token, or a reason there is none. */
sealed interface CredentialResult {
    data class Token(val value: String) : CredentialResult

    /** The user dismissed the sheet. Not a failure and never reported as one. */
    data object Cancelled : CredentialResult

    data class Failed(val reason: String) : CredentialResult
}

/**
 * Obtains a Google ID token through Credential Manager (docs/07 §13a).
 *
 * **Credential Manager and not `GoogleSignInClient`.** The latter is deprecated, and its one
 * failure mode — `DEVELOPER_ERROR`, status 10, for a missing SHA-1 — is famously unreadable.
 * The modern path reports the same condition as a `GetCredentialException` carrying a type.
 *
 * The **web** client id is correct here and is not a mistake: Credential Manager wants the
 * server client id that Google will mint the token *for*, and the Android client entry
 * (`client_type: 1`, created by registering the SHA-1) is what authorises this app to ask.
 * Both come from the same `google-services.json`; one is passed and one is not.
 *
 * Nothing here decides what the token means. It is handed to [LinkingAccountIdentity], which
 * links it to the uid this device already has.
 */
class GoogleCredentialRequest(
    private val context: Context,
    private val serverClientId: String,
) {

    companion object {
        private const val TAG = "PkAccount"
        private const val SERVER_CLIENT_ID_RESOURCE = "default_web_client_id"

        /**
         * The generated web client id, or `null` in a build with no `google-services.json`.
         *
         * Resolved by name rather than through `R.string`, and that is the whole point: the
         * resource is generated by the google-services plugin, and `app/build.gradle.kts`
         * applies that plugin only when the config file is present — CI and fork checkouts
         * have neither. A compile-time reference made those builds fail outright with
         * `UNRESOLVED_REFERENCE`, which is how this was found.
         */
        fun serverClientId(context: Context): String? {
            @Suppress("DiscouragedApi")
            val resource = context.resources.getIdentifier(
                SERVER_CLIENT_ID_RESOURCE,
                "string",
                context.packageName,
            )
            return if (resource == 0) null else context.getString(resource)
        }
    }

    suspend fun requestToken(): CredentialResult = try {
        val option = GetSignInWithGoogleOption.Builder(serverClientId).build()
        val request = GetCredentialRequest.Builder().addCredentialOption(option).build()
        val response = CredentialManager.create(context).getCredential(context, request)
        when (val credential = response.credential) {
            is CustomCredential -> {
                if (credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                    CredentialResult.Token(
                        GoogleIdTokenCredential.createFrom(credential.data).idToken,
                    )
                } else {
                    CredentialResult.Failed("unexpected credential type")
                }
            }
            else -> CredentialResult.Failed("unexpected credential class")
        }
    } catch (cancellation: CancellationException) {
        throw cancellation
    } catch (dismissed: GetCredentialCancellationException) {
        CredentialResult.Cancelled
    } catch (failure: GetCredentialException) {
        // Class name only: the message can carry the client id and account hints, and
        // docs/09 §11 keeps those out of the log.
        Log.i(TAG, "google credential unavailable: ${failure.javaClass.simpleName}")
        CredentialResult.Failed(failure.javaClass.simpleName)
    } catch (failure: Exception) {
        Log.i(TAG, "google credential failed: ${failure.javaClass.simpleName}")
        CredentialResult.Failed(failure.javaClass.simpleName)
    }
}
